from .aria2 import aria2_instance
from .mysql_service_manager import mysql_service_manager_instance
from .mysql_configuration import mysql_configuration_instance
from .qml_language import QmlLanguage
from .setting import setting_instance
from .system import system_instance
from .lanzou_parse import lanzou_parse_instance
from .crack import crack_instance
from .keyboard_listener import keyboard_listener_instance
from .host_edit import host_edit_instance
from .v2ray import v2ray_instance